### ISSUE TITLE
Please provide OpenCV version and other installation information.

### ISSUE THREAD

**Issue by homehacker** [jwcrawley/uWho#2]
Hi,

Couldn't get it to work with OpenCV 2.4.11.0 version even with https://github.com/itseez/opencv_contrib contribution modules.

I get these errors every time:

17:11:00: Running steps for project uWho...
17:11:00: Configuration unchanged, skipping qmake step.
17:11:00: Starting: "/usr/bin/make" 
g++ -c -m64 -pipe -O2 -Wall -W -D_REENTRANT -fPIE -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I../uWho -I../opencv/include -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I. -I. -I. -o mainwindow.o ../uWho/mainwindow.cpp
../uWho/mainwindow.cpp:16:39: fatal error: opencv2/contrib/contrib.hpp: No such file or directory
 #include <opencv2/contrib/contrib.hpp>
                                       ^

I have feeling that you have other version of OpenCV where are differences to mine. Therefore please provide installation information so others can replicate your installation properly.

**Comment by davidneudorfer** [comment]
+1

**Comment by jwcrawley** [comment]
Sorry. I was in talks with a venture capitalist over this technology. Because of that, I was developing privately on my own machine with this and a similar application.

Because that fell through, I'm continuing development on this.

I brought this current with OpenCV 3.0.0 with the contrib package as well (needs face module). I also develop in Qt 5.3.1, using QtCreator 3.1.2(Opensource).

I will be installing this on a clean Ubuntu 15.04 build within the next few days, so I will document the complete installation for the build environment.
